// File generated by FlutterFire CLI.
// Replace this stub by running `flutterfire configure` in the project root.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured. Run flutterfire configure.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'Platform ${defaultTargetPlatform.name} is not configured. '
          'Run flutterfire configure to regenerate this file.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeUwJPyWvfAgFmhkzmVFDTm5et1q4lVOQ',
    appId: '1:255546289414:android:4bacea98642db8fa0d4287',
    messagingSenderId: '255546289414',
    projectId: 'mosque-log',
    storageBucket: 'mosque-log.firebasestorage.app',
  );

  // PLACEHOLDER VALUES — replace by running `flutterfire configure`.
}